import './style.css';
import {meta,journey,method,schedule,prompts,demo,slides} from './content.js';

const base=import.meta.env.BASE_URL;
const app=document.querySelector('#app');
const routes=[['accueil','Accueil'],['module','Module 01'],['presentation','Présentation'],['demo','Démonstration'],['atelier','Mon atelier'],['ressources','Ressources'],['formateur','Formateur']];
const key='lnia-seance04-20261005-v1';
const fields=[
 ['alias','Pseudonyme ou identifiant candidat','Ex. Candidat 07'],
 ['activite','Votre activité ou projet','Ex. coach, enseignant, responsable de projet'],
 ['objectif','Votre objectif personnel','Ce que vous voulez produire et pourquoi'],
 ['public','Le public de votre production','Qui utilisera le résultat ?'],
 ['livrable','Le premier fichier à produire','Ex. fiche-accueil-v1.md'],
 ['entrees','Les informations confirmées et autorisées','Les seules données que l’IA peut utiliser'],
 ['manques','Les informations à confirmer','Ex. durée, modalités, source manquante'],
 ['controle','Votre critère de réussite','Ex. chaque affirmation repose sur une entrée fournie'],
 ['echeance','Votre échéance choisie','Une date réaliste ou « à confirmer »'],
 ['rythme','Votre rythme de travail','Ex. deux créneaux de vingt minutes par semaine'],
 ['engagement','Votre engagement relu','Ce que vous choisissez de produire, contrôler et conserver'],
 ['prompt','Le prompt réellement utilisé','Copiez la consigne envoyée à votre assistant'],
 ['resultat','Votre livrable corrigé','Collez votre résultat après relecture'],
 ['correction','Votre correction expliquée','Passage initial, problème, passage retenu et justification'],
 ['preuve','La preuve et sa date réelle','Nom du fichier rouvert, contrôle effectué et date'],
 ['retour','Le retour du binôme','Extrait autorisé, retour reçu et décision'],
 ['question','Votre question pour le module 02','Ce qui reste difficile dans votre prompt']
];
const checks=['Mon besoin et mon public sont explicites.','Les affirmations ont été contrôlées.','Les données partagées sont autorisées.','La correction est documentée.','Le fichier a été enregistré puis rouvert.'];
let state=Object.fromEntries(fields.map(([id])=>[id,'']));state.checks=[];
let slide=0,step=0,notes=false;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const notify=s=>{document.querySelector('#status').textContent=s;setTimeout(()=>document.querySelector('#status').textContent='',4500)};
function download(name,content,type='text/markdown;charset=utf-8'){
 const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);notify('Fichier téléchargé. Ouvrez-le pour vérifier son contenu.');
}
function copyText(text){
 if(navigator.clipboard&&window.isSecureContext)return navigator.clipboard.writeText(text).then(()=>notify('Texte copié.')).catch(()=>fallback(text));
 fallback(text);
}
function fallback(text){const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.top='0';document.body.append(area);area.select();try{if(document.execCommand('copy'))notify('Texte copié.');else notify('Copiez le texte affiché manuellement.')}catch{notify('Copiez le texte affiché manuellement.')}area.remove();}
function card(n,title,body){return `<article class="card"><span class="number">${n}</span><h3>${title}</h3><p>${body}</p></article>`}
function table(head,rows){return `<div class="table-wrap"><table><thead><tr>${head.map(x=>`<th scope="col">${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function title(k,h,p){return `<div class="page-title"><p class="eyebrow">${k}</p><h1>${h}</h1><p class="lead">${p}</p></div>`}
function markdown(text){return text.split('\n\n').map(p=>p.startsWith('## ')?`<h3>${esc(p.slice(3))}</h3>`:p.startsWith('# ')?`<h2>${esc(p.slice(2))}</h2>`:`<p>${esc(p).replaceAll('\n','<br>')}</p>`).join('');}
function shell(route,body){
 app.innerHTML=`<header class="header"><a class="brand" href="#accueil" aria-label="LN-IA accueil"><img src="${base}assets/logo-LN-IA.png" alt="Logo LN-IA"><span>Challenge 100 Jours<small>Relance Automne 2026</small></span></a><span class="date">Lundi 05 octobre 2026<span>Module 01 · Séance 04</span></span></header><nav class="nav" aria-label="Navigation principale">${routes.map(([id,label])=>`<a href="#${id}" ${route===id?'aria-current="page"':''}>${label}</a>`).join('')}</nav><main id="main" tabindex="-1">${body}</main><footer><div><strong>${meta.author}</strong><br>Professeur agrégé de physique · Formateur et coach</div><p>Apprendre en produisant. Produire avec méthode.<br>Partager avec valeur. Avancer avec conscience.</p><small>Version ${meta.version} · Support préparé pour le 05 octobre 2026<br>Le formateur réalise la validation pédagogique.</small></footer>`;
}
function home(){return `<section class="workshop-poster" aria-labelledby="poster-title"><div><p class="eyebrow">SÉANCE 04 · MODULE 01</p><h2 id="poster-title">Produire, contrôler, s’engager</h2><p>Transformez votre besoin en livrable vérifiable. Lundi 05 octobre 2026 · Horaire à confirmer.</p><a class="button navy" href="${base}assets/affiche-seance-04-LN-IA.png" download="affiche-seance-04-LN-IA.png">Télécharger l’affiche</a></div><a class="poster-image" href="${base}assets/affiche-seance-04-LN-IA.png" target="_blank" rel="noopener" aria-label="Ouvrir l’affiche de la séance 04 en grand"><img src="${base}assets/affiche-seance-04-LN-IA.png" alt="Affiche LN-IA : produire, contrôler, s’engager. Atelier du lundi 05 octobre 2026, animé par le Prof. Abderrahman EL HISSE." width="1122" height="1402" loading="lazy"></a></section><section class="hero"><div><p class="eyebrow">ATELIER PRATIQUE · SÉANCE 04</p><h1>Une production.<br>Un contrôle.<br><em>Une preuve.</em></h1><p>Vous avez un objectif et une carte des usages IA. Transformez maintenant un usage en livrable corrigé et en engagement concret.</p><div class="actions"><a class="button gold" href="#presentation">Ouvrir la présentation <span>→</span></a><a class="button outline" href="#atelier">Commencer mon atelier</a></div><p class="hero-meta">Lundi 05 octobre 2026 · 100 minutes proposées<br>Horaire à confirmer par le formateur</p></div><div class="hero-board"><p class="eyebrow">VOTRE DOSSIER DE FIN DE SÉANCE</p><div class="file"><span>01</span><div>Votre prompt<small>La consigne réellement utilisée</small></div><b>MD</b></div><div class="file"><span>02</span><div>Votre livrable<small>Une version corrigée</small></div><b>V2</b></div><div class="file"><span>03</span><div>Votre engagement<small>Une pratique que vous choisissez</small></div><b>MD</b></div><div class="file"><span>04</span><div>Votre preuve<small>Un contrôle daté et documenté</small></div><b>MD</b></div><p class="board-end">L’IA propose.<br>Vous vérifiez et décidez.</p></div></section><section><div class="section-heading"><p class="eyebrow">LE PROGRAMME</p><h2>Cent minutes pour passer à la pratique</h2></div><div class="schedule">${schedule.map(([time,t,p],i)=>`<article><span>${time}</span><div><h3>${i+1}. ${t}</h3><p>${p}</p></div></article>`).join('')}</div></section><section class="closing"><div><p class="eyebrow">AVANT DE COMMENCER</p><h2>Reprenez votre objectif et votre carte.</h2><p>Un besoin limité, des informations autorisées et un fichier que vous savez nommer.</p></div><a class="button navy" href="#module">Revoir le module 01 →</a></section>`}
function moduleView(){return title('COMPRENDRE','Le module 01 en quatre étapes','Vous apprenez à conduire une production de son besoin initial à sa preuve de contrôle.')+`<div class="journey">${journey.map(s=>`<article><span class="number">${s.n}</span><p class="eyebrow">${s.date} 2026</p><h2>${s.title}</h2><p>${s.text}</p><p class="proof">Trace attendue : ${s.proof}</p></article>`).join('')}</div><section><h2>Ce que l’IA apporte et ce que vous gardez</h2><div class="two"><article class="card"><p class="eyebrow">ASSISTANCE</p><h3>L’IA vous aide à produire</h3><ul><li>Clarifier une idée et proposer une structure.</li><li>Rédiger un brouillon à partir de votre contexte.</li><li>Comparer, reformuler et suggérer des corrections.</li></ul></article><article class="card"><p class="eyebrow">RESPONSABILITÉ</p><h3>Vous gardez le jugement</h3><ul><li>Choisir le besoin et les informations autorisées.</li><li>Vérifier les faits et l’utilité du résultat.</li><li>Décider des engagements, de la validation et de la diffusion.</li></ul></article></div><p>L’IA peut produire une information inventée ou oublier une contrainte. La validation LN-IA est une relecture pédagogique réalisée par une personne.</p></section><section><h2>Les outils ont des fonctions distinctes</h2>${table(['Outil','Usage dans l’atelier','Votre contrôle'],[['Assistant IA','Cadrer, rédiger et proposer des corrections.','Vérifier le contexte et les réponses.'],['Dossier personnel','Enregistrer et classer les productions.','Rouvrir le fichier pour vérifier la version.'],['Word et navigateur','Relire, mettre en forme et tester.','Ouvrir le livrable dans son format final.'],['Binôme','Relire un extrait autorisé.','Choisir et expliquer la correction retenue.']])}</section><section><h2>La méthode LN-IA</h2><div class="method">${method.map(([a,b],i)=>card(String(i+1).padStart(2,'0'),a,b)).join('')}</div></section><a class="button navy" href="#demo">Voir une démonstration complète →</a>`}
function presentation(){const s=slides[slide];return `<div class="presentation-tools"><p class="eyebrow">PRÉSENTATION CANDIDAT · 20 ÉCRANS</p><div class="actions"><button data-action="notes" aria-pressed="${notes}">${notes?'Masquer':'Afficher'} les notes</button><button data-action="fullscreen">Plein écran</button></div></div><div class="slide" id="slide"><p class="eyebrow">${esc(s.tag)} · ${String(slide+1).padStart(2,'0')}</p><h1>${esc(s.title)}</h1><p class="slide-sub">${esc(s.sub)}</p><ul>${s.items.map(i=>`<li>${esc(i)}</li>`).join('')}</ul><p class="slide-sign">LN-IA · Challenge 100 Jours · 05 octobre 2026</p></div>${notes?`<aside class="trainer-note"><strong>Note formateur</strong><p>${esc(s.note)}</p></aside>`:''}<div class="slide-controls"><button data-action="prev" ${slide===0?'disabled':''}>← Précédent</button><label for="slide-select">Écran <select id="slide-select">${slides.map((s,i)=>`<option value="${i}" ${i===slide?'selected':''}>${i+1} / ${slides.length} — ${esc(s.title)}</option>`).join('')}</select></label><button class="navy" data-action="next" ${slide===slides.length-1?'disabled':''}>Suivant →</button></div><p class="muted">Flèches gauche et droite pour naviguer. Échap quitte le plein écran.</p>`}
const demoSteps=['Cadrage','Prompt','Brouillon','Contrôle','Livrable','Preuve'];
function demoView(){let inner='';
 if(step===0)inner=`<p class="eyebrow">LE BESOIN</p><h2>Préparer une fiche d’accueil pour Madame Samira</h2><p>Livrable : une fiche de 150 à 220 mots expliquant le premier échange. Critères : public identifiable, cinq rubriques, aucune modalité inventée.</p><pre>${esc(demo.inputs)}</pre><h3>Plan de la démonstration en dix minutes</h3>${table(['Durée','Action'],[['1 min','Lire les entrées et le besoin.'],['2 min','Copier et expliquer le prompt.'],['2 min','Repérer les quatre erreurs du brouillon préparé.'],['3 min','Comparer avec la version corrigée.'],['2 min','Télécharger, rouvrir et noter le contrôle.']])}`;
 if(step===1)inner=`<p class="eyebrow">LA CONSIGNE</p><h2>Un prompt délimité par les données</h2><p>Pour une exécution réelle, copiez ce prompt dans votre assistant. Le résultat peut varier. Conservez la réponse réellement obtenue.</p><pre>${esc(demo.prompt)}</pre><button class="navy" data-action="copy-demo-prompt">Copier le prompt de démonstration</button>`;
 if(step===2)inner=`<p class="eyebrow">EXEMPLE D’ERREURS PRÉPARÉ</p><h2>Ce brouillon contient quatre problèmes</h2><p>Il sert à l’exercice de contrôle. Il ne s’agit pas d’une réponse produite en direct par un outil.</p><pre class="draft">${esc(demo.draft)}</pre><p>Repérez ce qui dépasse les informations autorisées avant de passer à l’étape suivante.</p>`;
 if(step===3)inner=`<p class="eyebrow">RELECTURE HUMAINE</p><h2>Chaque correction a une raison</h2>${table(['Passage','Problème','Correction'],demo.corrections)}<p>Vérifier ne consiste pas seulement à demander à l’IA si elle est sûre. Comparez la réponse aux informations de départ.</p>`;
 if(step===4)inner=`<p class="eyebrow">VERSION CORRIGÉE PRÉPARÉE</p><div class="document-preview">${markdown(demo.final)}</div><div class="actions"><button class="navy" data-action="download-demo">Télécharger la fiche corrigée</button><a class="button" href="${base}demonstration/fiche-accueil-corrigee.html" target="_blank" rel="noopener">Ouvrir le livrable HTML ↗</a></div>`;
 if(step===5)inner=`<p class="eyebrow">À EFFECTUER PENDANT L’ATELIER</p><h2>Une preuve se construit par vos actions</h2><ol><li>Téléchargez la fiche corrigée.</li><li>Ouvrez le fichier enregistré sur votre ordinateur.</li><li>Contrôlez les cinq rubriques et l’absence des quatre ajouts injustifiés.</li><li>Notez la date réelle, le nom du fichier et ce que vous avez vérifié.</li></ol><p>La démonstration fournit une version préparée. Votre réouverture et votre relecture constituent une nouvelle trace à renseigner.</p><a class="button navy" href="${base}modeles/preuves-module-01.md" download>Télécharger le modèle de preuve</a>`;
 return title('DÉMONSTRATION GUIDÉE','Du besoin au livrable corrigé',`${demo.person} · ${demo.activity}`)+`<p class="label">${demo.label}</p><div class="stepper" aria-label="Étapes de la démonstration">${demoSteps.map((s,i)=>`<button data-step="${i}" ${i===step?'aria-current="step"':''}>${i+1}. ${s}</button>`).join('')}</div><article class="demo-content">${inner}</article><div class="actions"><button data-action="demo-prev" ${step===0?'disabled':''}>← Étape précédente</button><button class="navy" data-action="demo-next" ${step===5?'disabled':''}>Étape suivante →</button><a class="text-link" href="#atelier">À vous de produire →</a></div>`;
}
function field(id){const f=fields.find(x=>x[0]===id);return `<div class="field"><label for="${id}">${f[1]}</label><textarea id="${id}" name="${id}" data-field="${id}" rows="${['resultat','prompt','correction'].includes(id)?5:2}" placeholder="${f[2]}">${esc(state[id])}</textarea></div>`;}
function workshop(){return title('MON ATELIER','Votre carnet de production','Complétez votre cadrage, travaillez dans votre assistant, puis conservez vos résultats ici.')+`<p class="local-info">Aucune donnée saisie n’est envoyée par ce site. Utilisez un pseudonyme. Le bouton « Enregistrer sur cet appareil » conserve votre brouillon dans ce navigateur. Exportez vos fichiers avant de quitter.</p><div class="actions"><button data-action="save">Enregistrer sur cet appareil</button><button data-action="restore">Reprendre le brouillon enregistré</button><button data-action="clear">Effacer mon brouillon</button></div><form id="workshop-form"><fieldset><legend>1 · Cadrer mon premier essai</legend><div class="form-grid">${['alias','activite','objectif','public','livrable','entrees','manques','controle'].map(field).join('')}</div></fieldset><fieldset><legend>2 · Choisir mon engagement</legend><div class="form-grid">${['echeance','rythme','engagement'].map(field).join('')}</div></fieldset><fieldset><legend>3 · Produire et documenter</legend><p>Le site n’exécute pas vos prompts. Utilisez l’assistant de votre choix et collez le résultat que vous avez relu.</p>${['prompt','resultat','correction','preuve','retour','question'].map(field).join('')}</fieldset><fieldset><legend>4 · Préparer la relecture humaine</legend>${checks.map((t,i)=>`<label class="check"><input type="checkbox" data-check="${i}" ${state.checks.includes(i)?'checked':''}>${t}</label>`).join('')}<p id="progress" class="progress">${progress()}</p><p>Ces cases expriment votre auto-évaluation. Le formateur apprécie les pièces et décide du statut pédagogique.</p></fieldset></form><section class="export"><h2>Exporter votre travail</h2><p>Chaque export reprend vos saisies. Les champs vides restent signalés « À compléter ».</p><div class="actions"><button class="navy" data-export="dossier">Télécharger mon dossier complet</button><button data-export="engagement">Mon engagement</button><button data-export="livrable">Mon livrable corrigé</button><button data-export="preuve">Ma preuve du module 01</button></div></section>`}
function progress(){return `${state.checks.length} / ${checks.length} contrôles déclarés · ${state.checks.length===checks.length?'À soumettre au formateur':'À compléter'}`}
const value=id=>state[id].trim()||'À compléter';
function exports(kind){let date=new Date().toLocaleString('fr-FR',{timeZone:'Africa/Casablanca'});const intro=`Séance 04 — Lundi 05 octobre 2026\nExporté le ${date} (Africa/Casablanca)\nPseudonyme : ${value('alias')}\nStatut : auto-évaluation, à relire par le formateur\n\n`;
 const engagement=`# Phrase d’engagement personnel\n\n${intro}## Mon engagement\n${value('engagement')}\n\n## Mon livrable et mon échéance\n${value('livrable')}\n${value('echeance')}\n\n## Ma régularité\n${value('rythme')}\n\n## Ma responsabilité\n${value('controle')}\n\n## Mes preuves\n${value('preuve')}`;
 const preuve=`# Preuves du module 01\n\n${intro}## Fichier corrigé\n${value('livrable')}\n\n## Contrôle réellement déclaré\n${value('preuve')}\n\n## Correction expliquée\n${value('correction')}\n\n## Retour de relecture\n${value('retour')}\n\n## Auto-évaluation\n${checks.map((c,i)=>`- [${state.checks.includes(i)?'x':' '}] ${c}`).join('\n')}\n\n## À compléter\n${value('manques')}\n\n## Question pour le module 02\n${value('question')}\n\nLa date d’export ne prouve pas une relecture. Le statut « validé » exige une décision humaine distincte.`;
 if(kind==='engagement')return ['phrase-engagement-personnel.md',engagement];
 if(kind==='preuve')return ['preuves-module-01.md',preuve];
 if(kind==='livrable')return ['livrable-corrige-seance-04.md',`# Livrable corrigé\n\n${intro}${value('resultat')}`];
 return ['dossier-atelier-seance-04.md',`# Mon dossier de séance 04\n\n${intro}${fields.map(([id,t])=>`## ${t}\n${value(id)}`).join('\n\n')}\n\n---\n\n${engagement}\n\n---\n\n${preuve}`];
}
function resources(){return title('RESSOURCES','Tous vos supports au même endroit','Des modèles à compléter et des prompts à adapter à votre projet.')+`<div class="two"><article class="card"><p class="eyebrow">GUIDE DU MODULE 01</p><h2>Les quatre séances réunies</h2><p>Rôles, outils, méthode, démonstration, exercices, engagement, confidentialité et preuves.</p><a class="button navy" href="${base}ressources/guide-complet-module-01-LN-IA.docx" download>Télécharger le guide Word</a><a class="text-link" href="${base}ressources/guide-complet-module-01-LN-IA.pdf" target="_blank" rel="noopener">Lire le guide PDF ↗</a></article><article class="card"><p class="eyebrow">DOSSIER CANDIDAT</p><h2>Vos modèles de travail</h2><p>Objectif, trois livrables, carte d’usages, cadrage, engagement, correction et preuves. Fiche d’identification vierge à conserver dans votre espace privé.</p><a class="button navy" href="${base}ressources/modeles-candidat-module-01.zip" download>Télécharger les modèles ZIP</a></article></div><section><h2>Prompts à copier</h2><p>Remplacez les champs entre crochets par des informations autorisées.</p>${prompts.map((p,i)=>`<details><summary>${i+1}. ${p.title}</summary><pre>${esc(p.text)}</pre><button data-prompt="${i}">Copier ce prompt</button></details>`).join('')}</section><section><h2>Reprendre les séances précédentes</h2><div class="resource-links"><a href="https://elhisse-clprepas.github.io/atelier-seance-01_25_SEPTEMBRE_2026/" target="_blank" rel="noopener">Séance 01 · Ouverture ↗</a><a href="https://elhisse-clprepas.github.io/Atelier-seance-02-28-Septembre-2026/" target="_blank" rel="noopener">Séance 02 · Objectif et livrables ↗</a><a href="https://elhisse-clprepas.github.io/Atelier-seance-03-02-Octobre-2026/" target="_blank" rel="noopener">Séance 03 · Usages IA ↗</a><a href="https://elhisse-clprepas.github.io/mini-site-seance-03-challenge-automne-2026/" target="_blank" rel="noopener">Présentation de la séance 03 ↗</a></div></section>`}
function trainer(){return title('CONDUITE DE SÉANCE','Faire produire et observer les contrôles','Le support candidat est prêt. Adaptez l’accompagnement au niveau du groupe.')+`<section><h2>Déroulé de 100 minutes</h2>${table(['Durée','Séquence','Résultat attendu'],schedule)}<p>La présentation sert de repère. Les rappels sont répartis dans l’atelier pour garder le temps de production.</p></section><section><h2>Préparer la rencontre</h2><ul><li>Ouvrir la présentation, la démonstration et un dossier de travail vide.</li><li>Tester le partage d’écran, le téléchargement et l’outil IA utilisé en direct.</li><li>Demander l’objectif et la carte d’usages de chaque candidat.</li><li>Rappeler le canal privé de remise de la fiche d’identification.</li><li>Prévoir un binôme et un extrait autorisé pour la relecture.</li></ul><p>Si l’IA n’est pas accessible, utiliser le brouillon préparé et faire réaliser les contrôles à partir des données du cas fictif.</p></section><section><h2>Observer des preuves, puis décider</h2>${table(['Critère','Pièce à observer'],[['Objectif et public','Cadrage rédigé en termes concrets.'],['Production','Fichier corrigé qui répond au besoin.'],['Contrôle','Une erreur ou une amélioration expliquée.'],['Engagement','Livrable, rythme réaliste et responsabilité humaine.'],['Confidentialité','Extrait partageable sans données privées inutiles.'],['Portfolio','Prompt, livrable et preuve datée retrouvables.']])}<p>Statuts proposés après relecture : « validé », « à compléter » ou « à revoir ». Le site n’attribue aucun statut de validation automatiquement.</p></section><section><h2>Adapter l’exercice</h2><div class="two">${card('A','Candidat débutant','Produire un texte court et un contrôle expliqué. Compléter les modèles avant de travailler sur la mise en forme.')}${card('B','Candidat autonome','Reprendre le même contenu dans un second format. Vérifier que les informations restent identiques.')}</div></section><section><h2>Préparer le module 02</h2><p>Demander le prompt réellement utilisé, le résultat obtenu et une difficulté précise. Ces trois pièces serviront à améliorer le contexte, les contraintes, le format et les critères de la prochaine demande.</p><a class="button navy" href="${base}ressources/guide-formateur-seance-04.md" download>Télécharger le conducteur formateur</a></section>`}
const views={accueil:home,module:moduleView,presentation,demo:demoView,atelier:workshop,ressources:resources,formateur:trainer};
function route(){const requested=location.hash.slice(1)||'accueil';const r=Object.hasOwn(views,requested)?requested:'accueil';shell(r,views[r]());document.title=`${routes.find(x=>x[0]===r)?.[1]||'Accueil'} — Séance 04 LN-IA`;}
window.addEventListener('hashchange',()=>{route();window.scrollTo(0,0);document.querySelector('#main').focus({preventScroll:true});});
app.addEventListener('input',e=>{if(e.target.dataset.field)state[e.target.dataset.field]=e.target.value;});
app.addEventListener('change',e=>{
 if(e.target.id==='slide-select'){slide=Number(e.target.value);route();}
 if(e.target.dataset.check!==undefined){const i=Number(e.target.dataset.check);state.checks=e.target.checked?[...new Set([...state.checks,i])]:state.checks.filter(n=>n!==i);document.querySelector('#progress').textContent=progress();}
});
app.addEventListener('submit',e=>e.preventDefault());
app.addEventListener('click',async e=>{
 const el=e.target.closest('button');if(!el)return;
 if(el.dataset.step!==undefined){step=Number(el.dataset.step);route();return;}
 if(el.dataset.prompt!==undefined){copyText(prompts[Number(el.dataset.prompt)].text);return;}
 if(el.dataset.export){const [name,content]=exports(el.dataset.export);download(name,content);return;}
 const a=el.dataset.action;
 if(a==='prev'||a==='next'){slide=Math.max(0,Math.min(slides.length-1,slide+(a==='next'?1:-1)));route();}
 if(a==='notes'){notes=!notes;route();}
 if(a==='fullscreen'){try{if(document.fullscreenElement){await document.exitFullscreen();document.body.classList.remove('presenting')}else{document.body.classList.add('presenting');await document.documentElement.requestFullscreen();}}catch{document.body.classList.remove('presenting');notify('Utilisez le mode plein écran de votre navigateur.');}}
 if(a==='demo-prev'||a==='demo-next'){step=Math.max(0,Math.min(5,step+(a==='demo-next'?1:-1)));route();}
 if(a==='copy-demo-prompt')copyText(demo.prompt);
 if(a==='download-demo')download('fiche-accueil-corrigee.md',demo.final);
 if(a==='save'){try{localStorage.setItem(key,JSON.stringify(state));notify('Brouillon enregistré dans ce navigateur.')}catch{notify('Enregistrement indisponible. Téléchargez votre dossier.')}}
 if(a==='restore'){try{const saved=JSON.parse(localStorage.getItem(key));if(!saved){notify('Aucun brouillon enregistré sur cet appareil.');return;}for(const [id] of fields)state[id]=typeof saved[id]==='string'?saved[id].slice(0,50000):'';state.checks=Array.isArray(saved.checks)?[...new Set(saved.checks.filter(n=>Number.isInteger(n)&&n>=0&&n<checks.length))]:[];route();notify('Brouillon repris.');}catch{notify('Brouillon illisible. Utilisez votre export.')}}
 if(a==='clear'&&confirm('Effacer les saisies et le brouillon enregistré sur cet appareil ? Les fichiers téléchargés seront conservés.')){state=Object.fromEntries(fields.map(([id])=>[id,'']));state.checks=[];try{localStorage.removeItem(key)}catch{}route();notify('Brouillon effacé.');}
});
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)document.body.classList.remove('presenting')});
document.addEventListener('keydown',e=>{if(location.hash!=='#presentation'||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();slide=Math.max(0,Math.min(slides.length-1,slide+(e.key==='ArrowRight'?1:-1)));route();}});
route();
